name: Build
on:
  push:
#    branches: [ $default-branch ]

jobs:
  build:
    name: Build Project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        build_type: [ Debug ]
        include:
          - os: windows-latest
            vcpkgCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
            triplet: x64-windows
    #          - os: ubuntu-latest
    #            vcpkgCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId}}'
          vcpkgJsonGlob: '**/Tracy.Native/vcpkg.json'

      - name: Build Tracy.Native
        uses: lukka/run-cmake@v10
        with:
          # This is the default path to the CMakeLists.txt along side the
          # CMakePresets.json. Change if you need have CMakeLists.txt and CMakePresets.json
          # located elsewhere.
          cmakeListsTxtPath: '${{ github.workspace }}/Tracy.Native/CMakeLists.txt'
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg

      - name: pwd
        run: pwd
      - name: ls
        run: ls -l

      - name: Restore Tracy.Net
        run: dotnet restore Tracy.Net

      - name: Build Tracy.Net
        run: dotnet build --no-restore Tracy.Net

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          if-no-files-found: error
          path: |
            bin\${{ matrix.build_type }}\Tracy.Native.dll
