name: Build
on:
  push:
#    branches: [ $default-branch ]

jobs:
  build:
    name: Build Project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            vcpkgCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
            triplet: x64-windows
    #          - os: ubuntu-latest
    #            vcpkgCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.local/share/NuGet/v3-cache
          key: ${{ runner.os }}-v1-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-v1-nuget-

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId}}'
          vcpkgJsonGlob: '**/Tracy.Native/vcpkg.json'

      - name: Build Tracy.Native
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/Tracy.Native/CMakeLists.txt'
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg

      - name: Restore Tracy
        run: dotnet restore Tracy

      - name: Build Tracy (Debug)
        run: dotnet build -c Debug --no-restore Tracy

      - name: Build Tracy (Release)
        run: dotnet build -c Release --no-restore Tracy

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          if-no-files-found: error
          path: |
            Tracy/bin
            Tracy.Native/
